package org.lazan.t5.graphael.components;

import java.util.List;

import org.apache.tapestry5.BindingConstants;
import org.apache.tapestry5.ComponentResources;
import org.apache.tapestry5.MarkupWriter;
import org.apache.tapestry5.annotations.AfterRenderBody;
import org.apache.tapestry5.annotations.BeginRender;
import org.apache.tapestry5.annotations.Import;
import org.apache.tapestry5.annotations.Parameter;
import org.apache.tapestry5.annotations.SetupRender;
import org.apache.tapestry5.annotations.SupportsInformalParameters;
import org.apache.tapestry5.dom.Element;
import org.apache.tapestry5.ioc.annotations.Inject;
import org.apache.tapestry5.ioc.internal.util.CollectionFactory;
import org.apache.tapestry5.json.JSONArray;
import org.apache.tapestry5.json.JSONObject;
import org.apache.tapestry5.runtime.RenderCommand;
import org.apache.tapestry5.services.Environment;
import org.apache.tapestry5.services.javascript.JavaScriptSupport;
import org.lazan.t5.graphael.model.LineModel;
import org.lazan.t5.graphael.model.LineSeriesModel;
import org.lazan.t5.graphael.model.Point;

@Import(library={ "raphael.js", "g.raphael-min.js", "g.line-min.js" })
@SupportsInformalParameters
public class LineChart {
	@Parameter(defaultPrefix=BindingConstants.LITERAL, required=true)
	private int locx;

	@Parameter(defaultPrefix=BindingConstants.LITERAL, required=true)
	private int locy;
	
	@Parameter(defaultPrefix=BindingConstants.LITERAL, required=true)
	private int width;

	@Parameter(defaultPrefix=BindingConstants.LITERAL, required=true)
	private int height;
	
	@Parameter(defaultPrefix=BindingConstants.LITERAL, name="options")
	private JSONObject optionsParam;

	@Parameter(defaultPrefix=BindingConstants.LITERAL)
	private RenderCommand postProcessor;
	
	private String postProcessorMarkup;
	
	@Inject
	private JavaScriptSupport jss;
	
	@Inject
	private Environment environment;
	
	@Inject
	private ComponentResources componentResources;
	
	private List<LineSeriesModel> seriesList;
	
	private boolean doColor;
	
	@SetupRender
	RenderCommand setupRender(MarkupWriter writer) {
		seriesList = CollectionFactory.newList();
		LineModel lineModel = new LineModel() {
			public void addSeries(LineSeriesModel series) {
				seriesList.add(series);
				if (series.getColor() != null) doColor = true;
			}
		};
		
		// push the model onto the environment so that child components can add to it
		environment.push(LineModel.class, lineModel);
		
		if (postProcessor != null) {
			// add a container to the DOM, this will be removed later
			writer.element("container");
			return postProcessor;
		}
		return null;
	}
	
	@BeginRender
	void beginRender(MarkupWriter writer) {
		if (postProcessor != null) {
			Element container = writer.getElement();
			
			// get the markup generated by the postProcessor RenderCommand
			postProcessorMarkup = container.getChildMarkup();
			writer.end();
			
			// remove the element from the DOM
			container.remove();
		}
	}
	
	@AfterRenderBody
	void afterRenderBody(MarkupWriter writer) {
		environment.pop(LineModel.class);

		String clientId = jss.allocateClientId(componentResources);
		writer.element("div", "id", clientId);
		componentResources.renderInformalParameters(writer);
		writer.end();
		JSONObject options = optionsParam == null ? new JSONObject() : new JSONObject(optionsParam.toCompactString());
		
		JSONArray allXValues = new JSONArray();
		JSONArray allYValues = new JSONArray();
		for (LineSeriesModel series : seriesList) {
			JSONArray xValues = new JSONArray();
			JSONArray yValues = new JSONArray();
			for (Point point : series.getValues()) {
				xValues.put(point.getX());
				yValues.put(point.getY());
			}
			allXValues.put(xValues);
			allYValues.put(yValues);
			
			if (doColor) options.append("colors", series.getColor());
		}
		String script = String.format(
			"var r = Raphael('%s'); " +
			"var chart = r.linechart(%s, %s, %s, %s, %s, %s, %s); ",
			clientId, locx, locy, width, height, allXValues.toCompactString(), allYValues.toCompactString(), options.toCompactString()
		);
		if (postProcessorMarkup != null) {
			script += String.format("(%s)(chart, r);", postProcessorMarkup);
		}
		jss.addScript(String.format("(function() {%s})()", script));
	}
}
